minimum_pre_commit_version: '2.17.0'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-xml
    - id: check-yaml
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: check-case-conflict
    - id: check-symlinks
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: mixed-line-ending
    - id: pretty-format-json
    - id: check-merge-conflict
      args: [--assume-in-merge]
- repo: https://github.com/shssoichiro/oxipng
  rev: v9.1.5
  hooks:
    - id: oxipng
      args: ["-o", "max", "--strip", "safe", "--alpha"]
      types: [png]
